version: '3.1'

services:
  server:
    image: testjunior:v1
    restart: always
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - DB_URI=mongodb://test:test1234@mongo:27017/
      - LOG_FILE=app.log
      - DB_NAME=junior_test
      - ACCESS_TOKEN_TTL=5m
      - REFRESH_TOKEN_TTL=24h
      - ACCESS_TOKEN_SECRET=access_token_super-secret
      - REFRESH_TOKEN_SECRET=refresh_token_super-secret
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test1234
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: test
      ME_CONFIG_MONGODB_ADMINPASSWORD: test1234
      ME_CONFIG_MONGODB_URL: mongodb://test:test1234@mongo:27017/